<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssetRipper.TextureDecoder" Version="2.6.0" />
    <PackageReference Include="BCnEncoder.Net" Version="2.2.1" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FastColoredTextBox.NET10" Version="2.16.26.9180" />
    <PackageReference Include="StbImageWriteSharp" Version="1.16.7" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Be.Windows.Forms.HexBox\Be.Windows.Forms.HexBox.csproj" />
    <ProjectReference Include="..\PictureBox\ImageViewControls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="all_properties.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="kidstypeinfodb.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Formats\KSCL\" />
  </ItemGroup>

</Project>
